### ISSUE TITLE
Widget content loading failed - Mixed HTTP & HTTPS content

### ISSUE THREAD

**Issue by drjagan** [oroinc/orocommerce#53]
Hello,
My fresh install of Orocommerce gives me a 'Widget content loading failed' error. 
Image: https://i.imgur.com/N2eYSwK.png
The Console of the Browser shows the following error:

`Mixed Content: The page at 'https://domain/app.php/admin/sale/quote/view/1?grid[quotes-grid]=i%3D1%26p%3D25%26s%255Bqid%255D%3D-1%26c%3Dqid1.customerUserName1.customerName1.internalStatusName1.customerStatusName1.ownerName1.expired1.validUntil1.poNumber1.shipUntil1.createdAt1.updatedAt1.workflowStepLabel1.payment_term_7c4f1e8e0%26v%3D__all__%26a%3Dgrid%26g%255BoriginalRoute%255D%3Doro_sale_quote_index' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://domain/app.php/admin/workflowwidget/transition/edit/attributes/32/send_to_customer_transition?_wid=3558bc1b-9458-4162-95b6-a9390831711c&_widgetContainer=dialog'. This request has been blocked; the content must be served over HTTPS.
`
Is this related to this [other issue](https://github.com/oroinc/platform/issues/219) on ORO platform?

**Comment by br0ther** [comment]
Hi drjagan! Thank you for submitting your query.
Could you please tell which version of OroCommerce and DB are you using?
This issue not related to mentioned [issue](https://github.com/oroinc/platform/issues/219).

If you load a page in your browser using HTTPS, the browser will refuse to load any resources over HTTP. Changing the API URL to have HTTPS instead of HTTP typically resolves this issue. For your case you are loading the
the page at `'https://domain/app.php/admin/sale/quote/view/1?grid[quotes-grid]=i%3D1%26p%3D25%26s%255B'`
but next request is going to http endpoint `'http://domain/app.php/admin/workflowwidget/transition'`. 

Could you please provide me with the steps to reproduce the issue?

**Comment by drjagan** [comment]
Dear @br0ther 
I am very sorry, I seem to have destroyed the VPS that had this error. I am unable to reproduce it now. 
It was the 1.4.0 version on MySQL database.

I am sorry I can't be of further help. 
I am enjoying a great installation of Orocommerce and it is fantastic. 
Thank you!
