### ISSUE TITLE
Install for test environment fails:

### ISSUE THREAD

**Issue by dimonixx** [oroinc/orocommerce#59]
OroCommerce version 1.5.1

`app/console oro:install --drop-database --env=test`

fails on `Oro\Bundle\TestFrameworkBundle\Migrations\Schema\OroTestFrameworkBundleInstaller` migration with following error:
`ERROR: Table "oro_ext_testentity1" has more than 1 class. Use "getEntityClassesByTableNames" method instead.`

**Comment by manowark** [comment]
Hi, @dimonixx.
Thank you for reporting the issue! We greatly appreciate all contributions to Oro projects.
I created internal task to fix this problem (INTERNAL ID: BAP-16343).

Also please clear `app/cache/test` folder in your application to solve this problem.
It described in https://oroinc.com/doc/orocommerce/current/install-upgrade/installation#re-installation and applicable for `test` environment too.

**Comment by dimonixx** [comment]
Hi @manowark ,

i've tried to clear cache, but this did not help.

**Comment by manowark** [comment]
Command `app/console cache:clear` will not help. You must have clear cache folder. Just use `rm -rf app/cache/test` in cli.

**Comment by dimonixx** [comment]
i've tried exactly  the way , you describe - got same error

**Comment by manowark** [comment]
All from the list?
1. Create new clear database.
2. Empty the <installation directory>/app/cache/test directory.
4. Clear the Installed option in the app/config/parameters_test.yml file and update the database name, if necessary.

If it will not help, please provide step by step manual how I can reproduce that issue like you. Because I did all rules from list and never see that problem.

**Comment by dimonixx** [comment]
I will try it once more :)

I have also never seen this problem till yesterday.

**Comment by manowark** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
