### ISSUE TITLE
composer install failure due to sebastian/phpcpd

### ISSUE THREAD

**Issue by tautelis** [oroinc/orocommerce#66]
```
Problem 1
    - Installation request for sebastian/phpcpd dev-master#cff7f36c2ae89d59987de25d14fd41a72dd4a703 as 3.1.0 -> satisfiable by sebastian/phpcpd[dev-master].
    - Conclusion: don't install phpunit/php-timer 1.0.9
    - sebastian/phpcpd dev-master requires phpunit/php-timer ^2.0 -> satisfiable by phpunit/php-timer[2.0.0, 2.0.x-dev].
    - Can only install one of: phpunit/php-timer[2.0.0, 1.0.9].
    - Can only install one of: phpunit/php-timer[2.0.x-dev, 1.0.9].
    - Installation request for phpunit/php-timer (locked at 1.0.9) -> satisfiable by phpunit/php-timer[1.0.9].
```

it seems like `dev-master#cff7f36c2ae89d59987de25d14fd41a72dd4a703 as 3.1.0` does not work and the latest dev-master commit is taken which has `phpunit/php-timer: 2.0.0` requirement.

**Comment by bemzaslava** [comment]
Hello, @tautelis 
Thank you for reporting the issue!

Yes, it's a known problem and it will be fixed in next repo sync. Please see an answer here
https://github.com/oroinc/platform-application/pull/16#issuecomment-363664492

If it blocks you, you can manually change version of sebastian/phpcpd to 3.0.*

**Comment by manowark** [comment]
I am now closing this issue as it is duplicate. Please, feel free to reopen it if you have any questions.
